<div class="page-title">
    <h1><?php echo Mage::helper('trustly')->__('Direct banking') ?></h1>
</div>
<p class="trustly_image"><img src="<?php echo $this->getSkinUrl('images/trustly-big.png'); ?>" alt="Trustly" /><p>

<?php if (!$this->getIframe()): ?>
<p class="note-msg"><?php echo Mage::helper('trustly')->__('Failed to display the payment method.') ?></p>
<?php else: ?>
<iframe src="<?php echo $this->getIframe(); ?>" style="min-height: 600px; border: 0; width: 100%; "></iframe>
<?php endif; ?>

<div class="buttons-set">
    <button type="button" title="<?php echo Mage::helper('trustly')->__('Cancel payment') ?>" class="button btn-continue" onclick="setLocation('<?php echo $this->getUrl('trustly/payment/cancel') ?>')"><span><span><?php echo Mage::helper('trustly')->__('Cancel payment') ?></span></span></button>
</div>
